id: I2B05392B
legacy_id: P006889
ocr_import_info:
  bdrc_scan_id: W2CZ7958
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T09:37:38'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T15:36:13.559144+00:00'
last_modified: 2022-09-02 23:38:48.180642
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ7958
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ7958
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བློ་གྲོས་བཟང་པོ།
  author: ཁྲི་ཚོ་མཁན་པོ་བློ་གྲོས་བཟང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.844793056287672
  ocr_word_median_confidence_index: 0.9200000166893005
quality: null
bases:
  I1KG9592:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9592
      total_pages: 631
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG9592.txt
    statistics:
      ocr_word_median_confidence_index: 0.8700000047683716
      ocr_word_mean_confidence_index: 0.8136223467347029
    legacy_id: v003
  I1KG9591:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9591
      total_pages: 491
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG9591.txt
    statistics:
      ocr_word_median_confidence_index: 0.949999988079071
      ocr_word_mean_confidence_index: 0.8776993808931896
    legacy_id: v002
  I1KG9590:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9590
      total_pages: 544
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG9590.txt
    statistics:
      ocr_word_median_confidence_index: 0.9300000071525574
      ocr_word_mean_confidence_index: 0.8500986549041899
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
